class Solution {
    public int uniquePaths(int m, int n) {
        int dp[][]=new int[m][n];
        for(int r[]:dp){
            Arrays.fill(r,-1);
        }
        return getans(0,0,m,n,dp);
    }
    static int getans(int s,int e,int r,int c,int mat[][]){
        if(s==r-1 && e==c-1) return 1;
        if(s>=r || e>=c) return 0;
        if(mat[s][e]!=-1) return mat[s][e];
        else return mat[s][e]=getans(s+1,e,r,c,mat)+getans(s,e+1,r,c,mat);
    }
}
